version: '3.7'
services:
  app:
    container_name: portfolio
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true